[package]
name = "messages_tauri"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
tauri = { version = "2.9.5", features = [] }
serde_json = "1.0"

[build-dependencies]
tauri-build = { version = "2.5.3", features = [] }
